name: display
description: "A new Flutter project."
publish_to: 'none'
version: 0.2.7+15

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  gap: ^3.0.1
  jovial_svg: ^1.1.21
  shadow_widget: ^0.1.1
  snow_widget:
    git: https://github.com/Punkachu/SnowingWidget
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/vectors/
  uses-material-design: true
